/*
 *
 * s_err.h  Automatically generated by Config.s_err script at Sat Jun 30 09:14:53 PDT 2001
 * by sortest
 *
 */

#define UCASE_SERVER_N "server"
#define LCASE_SERVER_N "server"
#define LCASE_CHAN_N "channel"
#define UCASE_CHAN_N "channel"
#define LCASE_USER_N "user"
#define UCASE_USER_N "user"
#define LCASE_OPER_N "operator"
#define UCASE_OPER_N "operator"
#define LCASE_NICK_N "nick"
#define UCASE_NICK_N "nick"
#define LU_INVIS "invisible"

#define WELC_MESSG "Welcome to the "NETWORK" IRC Network"
#define AWAY_MESSG 
#define UNAWAY_MESSG "You are no longer marked as being away"
#define OPER_MESSG "You are now an IRC " UCASE_OPER_N
#define WWAS_NONICK_N "nickname"
#define OPER_MESSG "You are now an IRC " UCASE_OPER_N
#define WWAS_NONICK_N "nickname"
#define PASSWD_MESSG "Password Incorrect"
#define KLINE_MESSG "You are banned from this server. Mail " KLINE_ADDRESS " for more information"
#define NOOPER_HOST "No O-lines for your host"
#define S_SERVER UCASE_SERVER_N
#define LU_USERS LCASE_USER_N "s"
#define LU_SERVERS LCASE_SERVER_N "s"
#define LU_OPER LCASE_OPER_N
#define LU_CHAN LCASE_CHAN_N "s"
#define LU_ME_C "clients"
#define REHASH_MESSG "Rehashing..."
#define NOSUCH_N LCASE_NICK_N"/"LCASE_CHAN_N
#define NOSUCH_S_N LCASE_SERVER_N
#define NOSUCH_C_N LCASE_CHAN_N
#define CHAN_NOSEND_N LCASE_CHAN_N
#define ISOPER_MESSG "is an IRC Operator"
